<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://www.example.org" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/FlightService/BudgetOutbound/BudgetOutboundBPEL"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://schemas.oracle.com/bpel/extension">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BudgetOutboundBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="BudgetOutboundRequest" namespace="http://www.example.org"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BudgetOutboundBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="BudgetFile" namespace="http://www.example.org"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [SAT MAR 11 11:37:10 EST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:BudgetFile >
         <ns0:InterfaceCode>
            <xsl:value-of select="/ns0:BudgetOutboundRequest/ns0:request/ns0:InterfaceCode"/>
         </ns0:InterfaceCode>
         <ns0:FileName>
            <xsl:value-of select="dvm:lookupValue ('BudgetDvm.dvm', 'interface_code', /ns0:BudgetOutboundRequest/ns0:request/ns0:InterfaceCode, 'target_file_name', 'Invalid' )"/>
         </ns0:FileName>
         <ns0:TempDir>
            <xsl:value-of select="dvm:lookupValue ('BudgetDvm.dvm', 'interface_code', /ns0:BudgetOutboundRequest/ns0:request/ns0:InterfaceCode, 'tmp_file_dir', 'Invalid' )"/>
         </ns0:TempDir>
      </ns0:BudgetFile>
   </xsl:template>
</xsl:stylesheet>
